apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviqtoolv3-deployment
spec:
  selector:
    matchLabels:
      app: deviqtoolv3
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: deviqtoolv3
    spec:
      containers:
      - name: deviqtoolv3
        image: chathurani/developerprodcutivitytrackerv2:1.0.0
        ports:
        - containerPort: 80
