name: CI/CD

on: push

jobs:
 build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chathurani/githubapipollinghandlerv1:1.0.0 
 job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A

    - name: Deploy deviqtool1-deployment microservice to minikube
      run:
         kubectl apply -f tool.yaml

    - name: Expose ports for Developertool
      run:
          kubectl expose deployment deviqtool1-deployment --type=NodePort --port=80

    - name: Get Deployement List
      run:
         kubectl get deployments
           
    - name:  Get url
      run:  minikube service deviqtool1-deployment --url
          echo "------------------opening the service------------------"
          curl $(minikube service  deviqtool1-deployment --url) 
     
