name: CI/CD

on: push

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chathurani/githubapipollinghandlerv1:1.0.0 
  job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
    - uses: actions/checkout@v2
    - name: Start minikube
      uses: medyagh/setup-minikube@master
    - name: Try the cluster !
      run: kubectl get pods -A
    - name: Build image
      run: |
        export SHELL=/bin/bash
        eval $(minikube -p minikube docker-env)
        docker build -f ./Dockerfile -t local/developerproductivitytool .
        echo -n "verifying images:"
        docker images        
    - name: Deploy developerproductivitytool microservice to minikube
      run:
        kubectl apply -f developerproductivity-deployment.yaml

    - name : Run Graphana
       run: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts


    - name: Deploy  githubpolling microservice to minikube
      run:
        kubectl apply -f RestApiPollingScheduler.yaml
        
    - name: Get Deployment List
      run:
        kubectl get deployment

    - name: Get Service List
      run:
        kubectl get svc
    - name: Get Pods List
      run:
        kubectl get pods

        
    - name: Install Ingress
      run: minikube addons enable ingress
      
    - name: Test service URLs developerproductivitytool1
      run: |
        minikube service list
        minikube service developerproductivitytool1 --url
        echo "------------------opening the service------------------"
        curl $(minikube service developerproductivitytool1 --url)   
        
    - name: Test service URLs restapipollinghandler
      run: |
        minikube service list
        minikube service restapipollinghandler --url
        echo "------------------opening the service------------------"
        curl $(minikube service restapipollinghandler --url)   
        
    - name: Install Ingress
      run: minikube addons enable ingress
