name: CI/CD

on: push

jobs:
 build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: chathurani/githubapipollinghandlerv1:1.0.0 
 job1:
    runs-on: ubuntu-latest
    name: build example and deploy to minikube
    steps:
      - name: Start minikube
        uses: medyagh/setup-minikube@master
      - name: Try the cluster !
        run: kubectl get pods -A
      
      - name: Debug
        run: |
           ls -al
      - name: Set Permissions
        run: chmod 600 IIT-2023.pem

      - name: Connect to EC2 Instance
        run: |
         ssh -i IIT-2023.pem ec2-user@54.166.162.94
           
   
